version: '3.4'

services:
  storeservices.api.author:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6405:80"

  storeservices.api.book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"

  storeservices.api.shoppingcart:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Book=http://storeservices.api.book
    ports:
      - "6106:80"

  storeservices.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Author=http://storeservices.api.gateway
    depends_on:
        - storeservices.api.book
    ports:
      - "6107:80"
